server:
  port: 8089

spring:
  datasource:
    url: jdbc:sqlite:D:\\Project\\JavaProject\\jcy_yc_backend\\src\\main\\resources\\jcyyc.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
